# Generated by Django 5.0.2 on 2024-02-29 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_group_student_studentlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentlesson',
            unique_together={('product', 'student')},
        ),
    ]
